### ISSUE TITLE
Cannot find module 'process-nextick-args'

### ISSUE THREAD

**Issue by bjakubiak** [sass/node-sass#1268]
npm fails to install node-sass.
It is reproducible with npm install ran for the first time with these dependencies in package.json:
```json
  "dependencies": {
    "gulp": "^3.5.6",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0",
    "gulp-sass": "^2.0.4"
  },
```
And here are errors:
```
> node-sass@3.4.2 install /Users/bartoszjakubiak/lab/npm/node_modules/node-sass
> node scripts/install.js

module.js:339
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/bartoszjakubiak/lab/npm/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:20:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.0
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.4.2 install: `node scripts/install.js`
npm ERR! Exit status 1
```

**Comment by bjakubiak** [comment]
It seems node-sass requires readable-stream which is not stated in its dependecies.

**Comment by xzyfer** [comment]
Node sass does not depend on readable-stream. This does not appear to be a
node-sass issue. Cannot reproduce with

```
npm install node-sass
```

**Comment by bjakubiak** [comment]
No such issue after upgrading npm to 3.5.3 - so seems like something caused by npm.

**Comment by kimegede** [comment]
See for help: https://gist.github.com/DanHerbert/9520689

**Comment by mshahin364** [comment]
You have need to installed **_node-sass_** as a devDependencies.

**Comment by smart-dream** [comment]
https://www.npmjs.com/package/process-nextick-args

**Comment by hermancito** [comment]
I solved doing
npm install -g --save process-nextick-args

**Comment by mx781** [comment]
Am still encountering this on Ubuntu 16.04 with node-sass@4.5.3 and npm 5.3.0 + node 8.1.3. Installing `process-nextick-args` globally does not seem to help.

**Comment by skygragon** [comment]
I hit same error with different modules. I have fixed it by deleting package-lock.json and clean node_modules/ and re-run `npm install`
