### ISSUE TITLE
CLI: watch doesnt work after upgrading to 4.6.0

### ISSUE THREAD

**Issue by samuelcecilio** [sass/node-sass#2139]
After upgrading from 4.5.3 the command below has stopped working. Changing the scss file does nothing:

`"css": "./node_modules/.bin/node-sass -w scss/style.scss public/css/style.css"`

- NPM version: 5.5.1
- Node version: 8.9.0
- Node Process:
  - http_parser: 2.7.0
  - node: 8.9.0
  - v8: 6.1.534.46
  - uv: 1.15.0
  - zlib: 1.2.11
  - ares: 1.10.1-DEV
  - modules: 57
  - nghttp2: 1.25.0
  - openssl: 1.0.2l
  - icu: 59.1
  - unicode: 9.0
  - cldr: 31.0.1
  - tz: 2017b
- Node Platform: linux
- Node architecture: x64
- npm node-sass versions: 4.6.0

**Comment by samuelcecilio** [comment]
Workaround

With the previous version the command works perfectly: `npm install node-sass@4.5.3`

**Comment by kurent** [comment]
I have the same issue. As @samuelcecilio mentioned, version 4.5.3 works fine

**Comment by edwardmelody** [comment]
I have too. Let's get back to version 4.5.3

**Comment by asommer70** [comment]
Using this command:

```
node-sass -w --output-style compressed -r ./scss --output ./public/css/
```

I get an error:

```
node/node_modules/node-sass/bin/node-sass:236
      if (watch.indexOf(file) === -1) {
                ^

TypeError: watch.indexOf is not a function
```

When I took a look at the **watch** object it's structured like:

```
{ '/scss/':
   [ '/scss/_includes.scss',
     '/scss/_settings.scss',
     '/scss/main.scss' ],
```
I removed the full path, but it's an object with key of directory path and an array of files in the directory.   The ```if (watch.index)``` on ***line 235** of **node-sass/bin/node-sass** isn't checking each of the keys in the object.... at least as far as I can tell.

Hope this helps.

**Comment by nichoth** [comment]
+1

**Comment by ChrisQuestad** [comment]
Thanks for finding this!

**Comment by rogerhokp** [comment]
+1 Same here....

**Comment by TFKED** [comment]
+1 downgrading to 4.5.3 fixed it for me too.

**Comment by evanfuture** [comment]
Hey, this is just a simple fix.  I've made a PR here: https://github.com/sass/node-sass/pull/2147

**Comment by xzyfer** [comment]
This is fixed in v4.6.1

**Comment by lucaseverett** [comment]
I'm having what appears to be this same issue when running the following. If I remove -w the file is output to my css folder, so I don't think I have a typo here. It seems that it isn't actually watching my _sass folder for changes.

"css-sass": "node-sass -w _sass --output css"

**Comment by samuelcecilio** [comment]
Not fixed. Same problem with `node-sass -w input.scss output.css`

`npm install node-sass@4.5.3` works fine

**Comment by nschonni** [comment]
@lucaseverett watch doesn't compile files till they are changed, don't use it as your compile script

**Comment by lucaseverett** [comment]
Yes, I'm aware of that, but in this case watch isn't detecting changes.

On Nov 13, 2017 12:31 PM, Nick Schonning <notifications@github.com> wrote:

@lucaseverett<https://github.com/lucaseverett> watch doesn't compile files till they are changed, don't use it as your compile script

**Comment by Stephen2** [comment]
Same behaviour - Windows 10 x64, node-sass 4.6.1

**Comment by xzyfer** [comment]
We've just released 4.7.1 with additional fixes for the watcher

**Comment by alexerhardt** [comment]
This issue persists in 4.7.2 -- moving back to 4.5.3 has fixed it.
