### ISSUE TITLE
c++ compiler reporting issues while installing node-sass

### ISSUE THREAD

**Issue by ravitadi** [sass/node-sass#1405]
```
`make: Entering directory `/home/test/testing/node_modules/gulp-sass/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DLIBSASS_VERSION="3.3.2"' -I/home/test/.node-gyp/0.12.7/include/node -I/home/test/.node-gyp/0.12.7/src -I/home/test/.node-gyp/0.12.7/deps/uv/include -I/home/test/.node-gyp/0.12.7/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -ffunction-sections -fdata-sections -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
In file included from ../src/libsass/src/ast.cpp:1:
../src/libsass/src/ast.hpp: In constructor ‘Sass::Hashed::Hashed(size_t)’:
../src/libsass/src/ast.hpp:246: error: ‘class std::unordered_map<Sass::Expression*, Sass::Expression*, std::hash<Sass::Expression*>, std::equal_to<Sass::Expression*>, std::allocator<std::pair<Sass::Expression* const, Sass::Expression*> > >’ has no member named ‘reserve’
../src/libsass/src/ast.hpp: In member function ‘Sass::Hashed& Sass::Hashed::operator+=(Sass::Hashed*)’:
../src/libsass/src/ast.hpp:275: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:279: error: could not convert ‘Sass::Hashed::reset_duplicate_key()’ to ‘bool’
../src/libsass/src/ast.hpp:280: error: expected primary-expression before ‘return’
../src/libsass/src/ast.hpp:280: error: expected ‘)’ before ‘return’
../src/libsass/src/ast.hpp: In member function ‘virtual size_t Sass::Map::hash()’:
../src/libsass/src/ast.hpp:872: error: expected initializer before ‘:’ token
../src/libsass/src/ast.hpp:876: error: expected primary-expression before ‘}’ token
../src/libsass/src/ast.hpp:876: error: expected ‘;’ before ‘}’ token
`
```

**Comment by saper** [comment]
You need to use g++ 4.8 or newer, clang also works.

**Comment by ravitadi** [comment]
@saper negative. I was using 4.7 on a centos and it is working fine. I tried it on a different centos with 4.7, fails. Closing this issue as upgrade does fix it but its strange that is works on 4.7 and fails in another.

**Comment by xzyfer** [comment]
It may have worked on 4.7 at some point. We only test and hence only
support 4.8.

**Comment by saper** [comment]
How "different" were those centos installs? Which libstdc++ were they using?

**Comment by ravitadi** [comment]
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2 - lib sass works

**Comment by saper** [comment]
That's surprising - do you have by chance a full compilation log with gcc 4.4?

**Comment by xzyfer** [comment]
@saper fwiw I believe the Linux binaries are built in centos 5 with GCC 4.x

**Comment by xzyfer** [comment]
4.4 or 4.5
